version: "3"

services:

  node1:
    build: .
    environment:
      SELF_ADDR: "node1:4321"
      PARTNERS: "node2:4321,node3:4321"
    hostname: node1
    ports: ["5001:5000", "4321"]
  
  node2:
    build: .
    environment:
      SELF_ADDR: "node2:4321"
      PARTNERS: "node1:4321,node3:4321"
    hostname: node2
    ports: ["5002:5000", "4321"]
  
  node3:
    build: .
    environment:
      SELF_ADDR: "node3:4321"
      PARTNERS: "node1:4321,node2:4321"
    hostname: node3
    ports: ["5003:5000", "4321"]
